### ISSUE TITLE
beginning-of-defun, end-of-defun &  mark-defun don't work

### ISSUE THREAD

**Issue by eallik** [hvesalai/scala-mode2#56]
These commands (`C-M-a`, `C-M-e`, `C-M-h`) don't seem to function at all in scala-mode2; however, these are highly productive commands when moving around and operating on source code; would it be realistic to hope that one day scala-mode2 will support these functions? I've verified that at least `c-mode`, `c++-mode, `python-mode` and `lisp-mode` support these functions, so most probably this is standard and can be expected by users to be available in scala-mode2 as well.

P.S. I'm aware of `C-c C-v .` as an alternative to `mark-defun`, but it's not really equivalent in speed.

**Comment by IvanMalison** [comment]
This can be closed now.

**Comment by eallik** [comment]
Cool!  so soon, if I update my emacs packages, it will work?

**Comment by IvanMalison** [comment]
Yep! There is a little quirk in its behavior that I just noticed where it will sometimes skip over two definitions. Its strange because if you call the scala-syntax function directly it does the right thing, but when it is called through end-of-defun, the behavior is slightly different.

The new version is already on melpa, so if you update right now you should get the new version.
